import Head from "next/head";
import { Navbar } from "@/components/layout/Navbar";
import { MainLayout } from "@/components/layout/MainLayout";
import { Footer } from "@/components/layout/Footer";
import { RevealLinks } from "@/components/layout/HeroSection";
import { DragCards } from "@/components/Card";
export default function Home() {
  return (
    <div>
      <Head>
        <title>SewaLapang</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> </link>
<link href="https://fonts.googleapis.com/css2?family=Contrail+One&family=Kite+One&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Oooh+Baby&family=Orelega+One&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Syne:wght@400..800&display=swap" rel="stylesheet"></link>
        <link rel="icon" href="/assets/faviconlogo.png" />
      </Head>
      <div className="font-contrail">
        <Navbar />
        <RevealLinks />
        <DragCards />

        <MainLayout />
        <Footer />
      </div>
    </div>
  );
}
