import Head from "next/head";
import { Navbar } from "@/components/layout/Navbar";
import { MainLayout } from "@/components/layout/MainLayout";
import { Footer } from "@/components/layout/Footer";
import { Navbar2 } from "@/components/layout/Navbar2";
export default function Home() {
  return (
    <div>
      <Head>
        <title>SewaLapang</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/faviconlogo.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Contrail+One&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div>
        <Navbar />
        <Navbar2 />
        <MainLayout />
        <Footer />
      </div>
    </div>
  );
}
