import {
  GiSoccerBall,
  GiShuttlecock,
  GiTennisRacket,
  GiHockey,
  GiRunningShoe,
} from "react-icons/gi";
import {
  MdOutlineSportsTennis,
  MdOutlineSportsVolleyball,
  MdOutlineSportsBasketball,
  MdSportsSoccer,
  MdSportsBaseball,
  MdSportsGolf,
  MdFitnessCenter,
  MdOutlineSports,
} from "react-icons/md";
import { PiSoccerBall, PiSpadeLight } from "react-icons/pi";
import { RiBilliardsFill } from "react-icons/ri";
import { TbPingPong, TbStretching2 } from "react-icons/tb";

export const imageMap = {
  default: [
    "https://img-cdn.medkomtek.com/1UDy5Oqu-0MLZ6euD8WDQixueJM=/0x0/smart/filters:quality(100):format(webp)/article/2IkVR6nR8uwlt_srzOfB6/original/070686200_1640338403-Cara-Memilih-Olahraga-yang-Cocok-2.jpg",
    "https://example.com/default-image2.jpg",
    "https://example.com/default-image3.jpg",
    "https://example.com/default-image4.jpg",
    "https://example.com/default-image5.jpg",
  ],
  "sepak bola": [
    "https://images.bisnis.com/posts/2024/11/13/1815710/rooms_inc_sepakbola_1_1731492481.jpg",
    "https://www.radioidola.com/wp-content/uploads/2024/11/2024-11-14_b8f5caae.jpg",
    "https://konisalatiga.or.id/wp-content/uploads/2017/05/HBFC.suratin.jpg",
    "https://awsimages.detik.net.id/community/media/visual/2024/04/26/timnas-indonesia-u-23-vs-korea-selatan-7.jpeg?w=1200",
    "https://akcdn.detik.net.id/community/media/visual/2023/09/28/timnas-indonesia-u-24_169.jpeg?w=1200",
  ],
  basketball: [
    "https://image.jpnn.com/resize/570x380-80/arsip/normal/2023/05/16/pebasket-kaleb-ramot-gemilang-saat-berlaga-pada-sea-games-20-bcl3.jpg",
    "https://image.jpnn.com/resize/570x380-80/arsip/normal/2023/05/16/timnas-basket-indonesia-gagal-melangkah-ke-final-sea-games-2-mwrh.jpg",
    "https://asset.indosport.com/article/image/q/80/345033/australia_v_indonesia_4-169.jpg?w=750&h=423&t=123",
    "https://akcdn.detik.net.id/community/media/visual/2023/05/11/timnas-basket-indonesia_169.jpeg?w=1200",
    "https://akcdn.detik.net.id/visual/2023/05/13/games-sea-1_169.jpeg?w=400&q=90",
  ],
  badminton: [
    GiShuttlecock,
    "https://example.com/badminton-image2.jpg",
    "https://example.com/badminton-image3.jpg",
    "https://example.com/badminton-image4.jpg",
    "https://example.com/badminton-image5.jpg",
  ],
  volley: [
    MdOutlineSportsVolleyball,
    "https://example.com/volley-image2.jpg",
    "https://example.com/volley-image3.jpg",
    "https://example.com/volley-image4.jpg",
    "https://example.com/volley-image5.jpg",
  ],
  tenis: [
    MdOutlineSportsTennis,
    "https://example.com/tenis-image2.jpg",
    "https://example.com/tenis-image3.jpg",
    "https://example.com/tenis-image4.jpg",
    "https://example.com/tenis-image5.jpg",
  ],
  billiard: [
    RiBilliardsFill,
    "https://example.com/billiard-image2.jpg",
    "https://example.com/billiard-image3.jpg",
    "https://example.com/billiard-image4.jpg",
    "https://example.com/billiard-image5.jpg",
  ],
  futsal: [
    MdSportsSoccer,
    "https://example.com/futsal-image2.jpg",
    "https://example.com/futsal-image3.jpg",
    "https://example.com/futsal-image4.jpg",
    "https://example.com/futsal-image5.jpg",
  ],
  baseball: [
    MdSportsBaseball,
    "https://example.com/baseball-image2.jpg",
    "https://example.com/baseball-image3.jpg",
    "https://example.com/baseball-image4.jpg",
    "https://example.com/baseball-image5.jpg",
  ],
  "mini soccer": [
    PiSoccerBall,
    "https://example.com/mini-soccer-image2.jpg",
    "https://example.com/mini-soccer-image3.jpg",
    "https://example.com/mini-soccer-image4.jpg",
    "https://example.com/mini-soccer-image5.jpg",
  ],
  "tenis meja": [
    TbPingPong,
    "https://example.com/tenis-meja-image2.jpg",
    "https://example.com/tenis-meja-image3.jpg",
    "https://example.com/tenis-meja-image4.jpg",
    "https://example.com/tenis-meja-image5.jpg",
  ],
  golf: [
    MdSportsGolf,
    "https://example.com/golf-image2.jpg",
    "https://example.com/golf-image3.jpg",
    "https://example.com/golf-image4.jpg",
    "https://example.com/golf-image5.jpg",
  ],
  padel: [
    PiSpadeLight,
    "https://example.com/padel-image2.jpg",
    "https://example.com/padel-image3.jpg",
    "https://example.com/padel-image4.jpg",
    "https://example.com/padel-image5.jpg",
  ],
  squash: [
    GiTennisRacket,
    "https://example.com/squash-image2.jpg",
    "https://example.com/squash-image3.jpg",
    "https://example.com/squash-image4.jpg",
    "https://example.com/squash-image5.jpg",
  ],
  hockey: [
    GiHockey,
    "https://example.com/hockey-image2.jpg",
    "https://example.com/hockey-image3.jpg",
    "https://example.com/hockey-image4.jpg",
    "https://example.com/hockey-image5.jpg",
  ],
  running: [
    GiRunningShoe,
    "https://example.com/running-image2.jpg",
    "https://example.com/running-image3.jpg",
    "https://example.com/running-image4.jpg",
    "https://example.com/running-image5.jpg",
  ],
  fitness: [
    MdFitnessCenter,
    "https://example.com/fitness-image2.jpg",
    "https://example.com/fitness-image3.jpg",
    "https://example.com/fitness-image4.jpg",
    "https://example.com/fitness-image5.jpg",
  ],
  aerobik: [
    TbStretching2,
    "https://example.com/aerobik-image2.jpg",
    "https://example.com/aerobik-image3.jpg",
    "https://example.com/aerobik-image4.jpg",
    "https://example.com/aerobik-image5.jpg",
  ],
};

export const iconMap = {
  default: MdOutlineSports,
  "sepak bola": GiSoccerBall,
  basketball: MdOutlineSportsBasketball,
  badminton: GiShuttlecock,
  volley: MdOutlineSportsVolleyball,
  tenis: MdOutlineSportsTennis,
  billiard: RiBilliardsFill,
  futsal: MdSportsSoccer,
  baseball: MdSportsBaseball,
  "mini soccer": PiSoccerBall,
  "tenis meja": TbPingPong,
  golf: MdSportsGolf,
  padel: PiSpadeLight,
  squash: GiTennisRacket,
  hockey: GiHockey,
  running: GiRunningShoe,
  fitness: MdFitnessCenter,
  aerobik: TbStretching2,
};
